### ISSUE TITLE
Set GITHUB_TOKEN for CI pipeline

### ISSUE THREAD

**Issue by zarfld** [zarfld/AVB-Windows#30]
ensure that the `GITHUB_TOKEN` environment variable is correctly set in your GitHub Actions workflow. The `GITHUB_TOKEN` is automatically provided by GitHub for authentication within workflows and can be used to interact with the GitHub API, such as creating issues.

## **1. Set the `GITHUB_TOKEN` Environment Variable in Your Workflow**

Modify your workflow file (e.g., `.github/workflows/ci.yml`) to set the `GITHUB_TOKEN` environment variable for the step where you run your Python script.

### **Example Workflow Configuration:**

```yaml
name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  issues: write  # Ensure the token has permission to create issues

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ... other steps ...

      - name: Build solution
        run: msbuild AVB_Windows.sln /p:Configuration=Release

      - name: Run Tests
        run: |
          # Run your tests here
          # If tests fail, the workflow will register failure()

      - name: Create Issue on Failure
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/issue_creation.py
```

**Explanation:**

- **`permissions` Block:** By setting `permissions: issues: write`, you grant the `GITHUB_TOKEN` the necessary permissions to create issues in the repository.
- **`env` Section:** The `GITHUB_TOKEN` is set in the environment variables for the step using `env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`.
- **`if: failure()`:** Ensures that the step only runs if previous steps failed.

---

## **2. Modify Your Python Script to Use the Environment Variable**

Ensure that your `issue_creation.py` script accesses the `GITHUB_TOKEN` environment variable correctly.

### **Example `issue_creation.py`:**

```python
import os
from github import Github

def create_github_issue(repo_name, title, body, labels):
    token = os.environ.get('GITHUB_TOKEN')
    if not token:
        raise ValueError("GITHUB_TOKEN environment variable not set")

    g = Github(token)
    repo = g.get_repo(repo_name)
    # ... rest of your code to create the issue ...

def main():
    repo_name = 'your-username/AVB-Windows'  # Replace with your repository
    title = 'Build Failure Detected'
    body = 'A build failure occurred in the CI pipeline.\n\nDetails:\n...'
    labels = ['build-failure']

    create_github_issue(repo_name, title, body, labels)

if __name__ == '__main__':
    main()
```

**Ensure:**

- The script uses `os.environ.get('GITHUB_TOKEN')` to access the token.
- The script handles the case where the token is not set.

---

## **3. Verify Token Permissions**

The `GITHUB_TOKEN` must have the necessary permissions to create issues.

- By default, the `GITHUB_TOKEN` has a set of permissions, but you can explicitly set them in your workflow file.
- In your workflow, under the `permissions` key, specify:

  ```yaml
  permissions:
    issues: write
  ```

This ensures that the token can create and modify issues.

---

## **4. Ensure Secure Handling of Secrets**

- **Do Not Print Secrets:** Make sure your script does not print the `GITHUB_TOKEN` or any sensitive information to the logs.
- **Use `secrets.GITHUB_TOKEN`:** GitHub Actions automatically provides the `GITHUB_TOKEN` in `secrets.GITHUB_TOKEN`.

---

## **5. Complete Example of the Workflow File**

Here's the complete `ci.yml` workflow file incorporating all the above steps:

```yaml
name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  issues: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore AVB_Windows.sln

      - name: Build solution
        run: msbuild AVB_Windows.sln /p:Configuration=Release

      - name: Run Tests
        run: |
          # Run your tests here
          # If tests fail, the workflow will register failure()

      - name: Create Issue on Failure
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/issue_creation.py
```

---

## **6. Test Your Workflow**

- **Introduce a Failure:** Temporarily modify your code or tests to cause a failure.
- **Observe the Workflow:** Verify that the `Create Issue on Failure` step runs and that an issue is created in your repository.
- **Check the Issue:** Ensure that the issue contains the expected title, body, and labels.

---

## **7. Alternative Method: Use `actions/github-script`**

If you prefer not to write your own script, you can use the `actions/github-script` action to create the issue directly in your workflow.

### **Example:**

```yaml
- name: Create Issue on Failure
  if: failure()
  uses: actions/github-script@v6
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    script: |
      const title = `Build Failure on ${context.ref}`;
      const body = `
      **Build failed on commit ${context.sha}**

      Error Details:
      ${require('fs').readFileSync('path/to/error_summary.txt', 'utf8')}

      [View Build Logs](${context.runUrl})
      `;
      const { data: issues } = await github.rest.issues.listForRepo({
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: 'build-failure',
        state: 'open',
      });
      const duplicate = issues.find(issue => issue.title === title);
      if (!duplicate) {
        await github.rest.issues.create({
          owner: context.repo.owner,
          repo: context.repo.repo,
          title,
          body,
          labels: ['build-failure'],
        });
      } else {
        await github.rest.issues.createComment({
          owner: context.repo.owner,
          repo: context.repo.repo,
          issue_number: duplicate.number,
          body: `Another occurrence on commit ${context.sha}`,
        });
      }
```

**Note:**

- This method avoids the need to manage the `GITHUB_TOKEN` in your script explicitly.
- The `actions/github-script` action handles authentication automatically using the provided `github-token`.

---

## **8. Additional Considerations**

- **Rate Limits:** Be mindful of GitHub API rate limits when creating issues programmatically.
- **Duplicate Issues:** Implement logic to prevent creating duplicate issues for the same error.
- **Sensitive Information:** Ensure that error messages do not contain sensitive information before including them in issue descriptions.

---

## **9. Troubleshooting**

- **Environment Variable Not Set:**
  - Verify that the `env` block is correctly indented and associated with the correct step.
  - Ensure you're using `${{ secrets.GITHUB_TOKEN }}` and not `${{ env.GITHUB_TOKEN }}`.
- **Permissions Error:**
  - If you receive a permissions error, double-check the `permissions` block in your workflow.
  - Ensure that the `GITHUB_TOKEN` has `issues: write` permission.

---

## **10. Security Best Practices**

- **Keep the `GITHUB_TOKEN` Secure:** Do not expose the token in logs or error messages.
- **Use Least Privilege:** Only grant the necessary permissions required for the token.
- **Regularly Review Workflow Files:** Ensure that no secrets are hard-coded or improperly exposed.

---

By following these steps, you should be able to set the `GITHUB_TOKEN` environment variable in your GitHub Actions workflow, prevent the error, and successfully create issues when build failures occur.

**Feel free to ask if you have any more questions or need further assistance!**
